# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/sikalabsx/master"
  version "2026.2.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabsx/master/releases/download/v2026.2.15/master_v2026.2.15_darwin_amd64.tar.gz"
      sha256 "71c67bb2018d1ab93776cf370380353f873eee15695bb1a99cb395dfe7cec4cd"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
        bin.install "master_mon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabsx/master/releases/download/v2026.2.15/master_v2026.2.15_darwin_arm64.tar.gz"
      sha256 "dad1c99cc0086b46074f9dfe0c22645421eeffb5ebafde0b83d6e337d340a990"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
        bin.install "master_mon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2026.2.15/master_v2026.2.15_linux_amd64.tar.gz"
      sha256 "32676df88ffc1422485fb2d8ecb7a5369a90ac01efc41675ac2d3efc94324c53"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
        bin.install "master_mon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2026.2.15/master_v2026.2.15_linux_arm64.tar.gz"
      sha256 "63d86f1e917335c91c80c831693c0c8a297153e92d86e85a4b2569c4c1bf5d65"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
        bin.install "master_mon"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabsx/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
