# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/sikalabsx/master"
  version "2025.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabsx/master/releases/download/v2025.11.0/master_v2025.11.0_darwin_amd64.tar.gz"
      sha256 "7ad09f4352c3533122bf8ac2d45f9c4937d1674b35eaebe4123836f3c988788d"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabsx/master/releases/download/v2025.11.0/master_v2025.11.0_darwin_arm64.tar.gz"
      sha256 "8173df159749615108c447dc31a9250b89cbb2345fb94f61a1b3e7df637816d6"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2025.11.0/master_v2025.11.0_linux_amd64.tar.gz"
      sha256 "410f0ea441268ab8ae9582e31cd85e71e848ab8e723f72f82ace96bf18f4cce4"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2025.11.0/master_v2025.11.0_linux_arm64.tar.gz"
      sha256 "bf7ba4d7a7df72e37007fcca5b8000694af8b6ebd6e1c535c315678b1bcbab57"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabsx/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
