# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Master < Formula
  desc "master"
  homepage "https://github.com/sikalabsx/master"
  version "2025.10.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabsx/master/releases/download/v2025.10.16/master_v2025.10.16_darwin_amd64.tar.gz"
      sha256 "1b8b8689e311a077f15de23efbf7081ec7e7d3e0d6bfd8e0e103df0d08c4b426"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabsx/master/releases/download/v2025.10.16/master_v2025.10.16_darwin_arm64.tar.gz"
      sha256 "ddb2fc88dd5e66a1845740c04d0e711376bd7cf72c5ff44aa2227348b1612d80"

      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2025.10.16/master_v2025.10.16_linux_amd64.tar.gz"
      sha256 "d927f4f39433420281a5ee1a7b1abd2d5fcf6bf8216cd4ae4ae87bde37887859"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/master/releases/download/v2025.10.16/master_v2025.10.16_linux_arm64.tar.gz"
      sha256 "6c46e2f3d586c8634b136982d4245bb5f51a8dc738f358e01afdca792d30eedd"
      def install
        bin.install "master"
        bin.install "master_slu"
        bin.install "master_slr"
        bin.install "master_tergum"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabsx/master
    EOS
  end

  test do
    system "#{bin}/master version"
  end
end
