# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class V7y < Formula
  desc "v7y"
  homepage "https://github.com/sikalabsx/v7y"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabsx/v7y/releases/download/v0.1.0/v7y_v0.1.0_darwin_amd64.tar.gz"
      sha256 "fccb1547ed23c4016459d389aa0bbcb393835318b8f58c9c9fb2777eb6070428"

      def install
        bin.install "v7y"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabsx/v7y/releases/download/v0.1.0/v7y_v0.1.0_darwin_arm64.tar.gz"
      sha256 "17fac48531a8c0093d5fd601a8a191596f388829e96f6b92ca34383a2d6c215f"

      def install
        bin.install "v7y"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/v7y/releases/download/v0.1.0/v7y_v0.1.0_linux_amd64.tar.gz"
      sha256 "09c13f7a07f51471fa1d43274564ce4d0c2aa83ac1589a71c657c9b47cb13802"
      def install
        bin.install "v7y"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabsx/v7y/releases/download/v0.1.0/v7y_v0.1.0_linux_arm64.tar.gz"
      sha256 "4826dcd75fe79417638a14ff470b9b3fa7f23082c19d20a2a9c19c568fdde375"
      def install
        bin.install "v7y"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabsx/v7y
    EOS
  end

  test do
    system "#{bin}/v7y --version"
  end
end
